### ISSUE TITLE
Add Tab Name or Label to the Tab Bar

### ISSUE THREAD

**Issue by tradebulls** [Jm-Zion/rn-wave-bottom-bar#38]
Hi @Jm-Zion, 

Thanks for the great library. It works like charm. One thing I would like to add yo my tabBar was the name or the label of the tabBar. Given the animating tab, is there any possibility of adding the label to the tab bar or at least to the tabs which are inactive currently.

Any help would be great. Thanks a ton.

**Comment by J3j3m** [comment]
Hi, this a great idea. I'll give it a try.

**Comment by Jm-Zion** [comment]
Hi, i've just published a new version with label support, let me know what you think about the feature :)

**Comment by tradebulls** [comment]
Looks amazing. Thanks for the support :)
