### ISSUE TITLE
focused button issue

### ISSUE THREAD

**Issue by Mudassirhasan** [Jm-Zion/rn-wave-bottom-bar#396]
Hi, for bottom navigation in react native version "0.70.6", the focused button is not getting hidden for inactive tabs. For react native version 0.69 it is working perfectly fine. Attaching the video for reference.
![Simulator Screen Shot - iPhone 14 - 2022-12-08 at 15 52 40](https://user-images.githubusercontent.com/42797571/206425347-de9ee276-1a33-4607-85fe-8435ead8c5f8.png)

https://user-images.githubusercontent.com/42797571/206425268-866efa88-15bc-4083-9a32-bedeaac0e5c5.mp4

**Comment by Jm-Zion** [comment]
Hi, thank you for the feedback.
I'll try to take time to fix that this weekend.

**Comment by Mudassirhasan** [comment]
Hi, @Jm-Zion any updates on this?

**Comment by rodrigodiasf1984** [comment]
![image](https://user-images.githubusercontent.com/30758309/207043189-6710c125-14ad-4533-bc6e-81acae2ecad1.png)
same problem here
My libs: 
    "@react-navigation/bottom-tabs": "^6.5.1",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",
    "@react-navigation/stack": "^6.3.4",
    "react": "18.1.0",
    "react-native": "0.70.6",
    "react-native-gesture-handler": "~2.8.0",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "~3.18.0",
    "rn-wave-bottom-bar": "^2.2.0",

**Comment by Jm-Zion** [comment]
Bug has been fixed, let me know if you still have the issue.
