### ISSUE TITLE
Issue with react-native-safe-area-context

### ISSUE THREAD

**Issue by alz10** [Jm-Zion/rn-wave-bottom-bar#46]
After upgrading my react native version to `0.67.3`, i got this error

dependencies
```
"react": "17.0.2",
"react-native": "0.67.3",
"rn-wave-bottom-bar": "^2.1.1"
"react-native-safe-area-context": "^4.1.2",
"@react-navigation/bottom-tabs": "^6.2.0",
```

![issue](https://user-images.githubusercontent.com/38030623/157814554-87dbbe3a-7be8-4ee0-993f-7e3f8ee915cc.png)

**Comment by alz10** [comment]
It's working now but i had to downgrade `"react-native-safe-area-context"` to `^3.4.1"`
latest version `(^4.1.2)` causes the error above

**Comment by Jm-Zion** [comment]
Thank you for the report, will give a check very soon

**Comment by tradebulls** [comment]
We are facing same issue
