### ISSUE TITLE
Setting speed movement for circle/square button active

### ISSUE THREAD

**Issue by cause-pasca** [Jm-Zion/rn-wave-bottom-bar#47]
It is possible to set the speed movement for circle/square button active? i know there is props springConfig, but after iam working with it, it seem like to config the animation for the tab bar not the button active, thank you for the respons.

**Comment by Jm-Zion** [comment]
Hello, 
Yes you can play around adding springConfig object to BottomFabBar component :
`              springConfig={{
                stiffness: 1500,
                damping: 85,
                mass: 4,
              }}
`
feel free to reopen if needed.
