### ISSUE TITLE
color

### ISSUE THREAD

**Issue by maxpill** [Jm-Zion/rn-wave-bottom-bar#5]
how to change the navigation bar white background color to transparent? I mean the color which is behind the selected tab

**Comment by maxpill** [comment]
@Jm-Zion

**Comment by Jm-Zion** [comment]
Sorry for the delayed response, I will take a look at it asap.

**Comment by maxpill** [comment]
No problem, if you need more information what exactly the problem is, I'll write you a message or email

**Comment by maxpill** [comment]
![IMG_20200901_084010.jpg](https://user-images.githubusercontent.com/43760021/91810801-cec6b080-ec2e-11ea-9087-96434e3855d1.jpg)

My goal is have my map visible behind the bar. As you can see, there is a white area behind the bar. From my research it is caused because the map isn't even rendered behind the bar that why setting the background color of this component to transparent doesn't do the work.

**Comment by Jm-Zion** [comment]
I pushed some modifications that allows you to customize the barContainerStyle itself, take a look at the sample, feel free to re-open if it did not resolve your problem.

**Comment by maxpill** [comment]
Works like a charm. :) Thank you very much. Don't forget to push an update to npm.

**Comment by maxpill** [comment]
![bez nazwy](https://user-images.githubusercontent.com/43760021/91993304-7f1edc80-ed35-11ea-9114-d9208bf37e6c.png)
